### PR TITLE
MdeModulePkg/Universal: Fix several build issues for clang 

### LINKED ISSUE #11786: [Bug]: SetupBrowserDxe build fails with CLANGPDB
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

MdeModulePkg

### Which targets are impacted by this bug?

DEBUG

### Current Behavior

Build fails with clang 21.1.6 due uninitialized variables. Variables 'Storage' and 'BrowserStorage' resulted:
-Werror,-Wsometimes-uninitialized

### Expected Behavior

Build with clang 21.1.6 to be successful.

### Steps To Reproduce

1. Install clang and required toolchain like LLVM and lld.
2. Build with OVMF target architecture X64.
3. Make sure MdeModulePkg/Universal/SetupBrowserDxe is included in the build
4. It should fail with provided build errors

### Build Environment

```markdown
- OS(s): Arch Linux
- Tool Chain(s): CLANGPDB
```

### Version Information

```text
Commit: 1436aea4d57 - 1436aea4d57
```

### Urgency

High

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

`make: Nothing to be done for 'tbuild'.
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:9: error: variable 'Storage' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  456 |     if (StorageName == NULL) {
      |         ^~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:523:7: note: uninitialized use occurs here
  523 |   if (Storage != NULL) {
      |       ^~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:5: note: remove the 'if' if its condition is always false
Building ... /home/khaalid/edk2/SecurityPkg/Hash2DxeCrypto/Hash2DxeCrypto.inf [X64]
  456 |     if (StorageName == NULL) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |       ASSERT (StorageName != NULL);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  458 |       goto ErrorExit;
      |       ~~~~~~~~~~~~~~~
  459 |     }
      |     ~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:426:28: note: initialize the variable 'Storage' to silence this warning
  426 |   FORMSET_STORAGE  *Storage;
      |                            ^
      |                             = NULL
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:470:7: error: variable 'BrowserStorage' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  470 |   if (Storage == NULL) {
      |       ^~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:519:7: note: uninitialized use occurs here
  519 |   if (BrowserStorage != NULL) {
      |       ^~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:470:3: note: remove the 'if' if its condition is always false
  470 |   if (Storage == NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~
  471 |     ASSERT (Storage != NULL);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~
  472 |     goto ErrorExit;
      |     ~~~~~~~~~~~~~~~
  473 |   }
      |   ~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:9: error: variable 'BrowserStorage' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  456 |     if (StorageName == NULL) {
      |         ^~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:519:7: note: uninitialized use occurs here
  519 |   if (BrowserStorage != NULL) {
      |       ^~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:5: note: remove the 'if' if its condition is always false
  456 |     if (StorageName == NULL) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |       ASSERT (StorageName != NULL);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  458 |       goto ErrorExit;
      |       ~~~~~~~~~~~~~~~
  459 |     }
      |     ~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:429:35: note: initialize the variable 'BrowserStorage' to silence this warning
  429 |   BROWSER_STORAGE  *BrowserStorage;
      |                                   ^
      |                                    = NULL
`

### LINKED ISSUE #11787: [Bug]: HiiDatabaseDxe build fails with CLANGPDB
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

MdeModulePkg

### Which targets are impacted by this bug?

DEBUG

### Current Behavior

Build fails with clang 21.1.6 due uninitialized Status variable.

### Expected Behavior

Build to be successful

### Steps To Reproduce

1. Install clang and required toolchain like LLVM and lld.
2. Build OVMF with target X64.
3. Make sure HiiDatabaseDxe is included.

### Build Environment

```markdown
- OS(s): ArchLinux
- Tool Chain(s): CLANGPDB
```

### Version Information

```text
Commit: 1436aea4d57
```

### Urgency

High

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

`/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:895:9: error: variable 'Status' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
  895 |     if (*ConfigAltResp == NULL) {
      |         ^~~~~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:910:10: note: uninitialized use occurs here
  910 |   return Status;
      |          ^~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:895:5: note: remove the 'if' if its condition is always true
  895 |     if (*ConfigAltResp == NULL) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:885:7: error: variable 'Status' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
  885 |   if (AppendString != NULL) {
      |       ^~~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:910:10: note: uninitialized use occurs here
  910 |   return Status;
      |          ^~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:885:3: note: remove the 'if' if its condition is always true
  885 |   if (AppendString != NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:832:9: error: variable 'Status' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  832 |     if (NvConfigValuePtr == NULL) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:910:10: note: uninitialized use occurs here
  910 |   return Status;
      |          ^~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:832:5: note: remove the 'if' if its condition is always false
  832 |     if (NvConfigValuePtr == NULL) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  833 |       ASSERT (NvConfigValuePtr != NULL);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  834 |       goto Exit;
      |       ~~~~~~~~~~
  835 |     }
      |     ~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:820:7: error: variable 'Status' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  820 |   if (StringPtr == NULL) {
      |       ^~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:910:10: note: uninitialized use occurs here
  910 |   return Status;
      |          ^~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:820:3: note: remove the 'if' if its condition is always false
  820 |   if (StringPtr == NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
  821 |     ASSERT (StringPtr != NULL);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  822 |     goto Exit;
      |     ~~~~~~~~~~
  823 |   }
      |   ~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:814:7: error: variable 'Status' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  814 |   if (StringPtr == NULL) {
      |       ^~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:910:10: note: uninitialized use occurs here
  910 |   return Status;
      |          ^~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:814:3: note: remove the 'if' if its condition is always false
  814 |   if (StringPtr == NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
  815 |     ASSERT (StringPtr != NULL);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  816 |     goto Exit;
      |     ~~~~~~~~~~
  817 |   }
      |   ~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:804:7: error: variable 'Status' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  804 |   if (NvConfigPtr == NULL) {
      |       ^~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:910:10: note: uninitialized use occurs here
  910 |   return Status;
      |          ^~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:804:3: note: remove the 'if' if its condition is always false
Building ... /home/khaalid/edk2/MdePkg/Library/DxeCoreHobLib/DxeCoreHobLib.inf [X64]
  804 |   if (NvConfigPtr == NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
  805 |     ASSERT (NvConfigPtr != NULL);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  806 |     goto Exit;
      |     ~~~~~~~~~~
  807 |   }
      |   ~
make: Nothing to be done for 'tbuild'.
/home/khaalid/edk2/MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c:785:21: note: initialize the variable 'Status' to silence this warning
  785 |   EFI_STATUS  Status;
      |                     ^
      |    `

### LINKED ISSUE #11793: [Bug]: BdsDxe build fails with CLANGPDB
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

MdeModulePkg

### Which targets are impacted by this bug?

DEBUG

### Current Behavior

Build fails with clang 21.1.6.

### Expected Behavior

Build to be successful with CLANGPDB 

### Steps To Reproduce

1. Install clang and required toolchain like LLVM and LLd
2. build OVMF image with target architecture X64 
3. it should fail with supplied build errors

### Build Environment

```markdown
- OS(s): Arch Linux
- Tool Chain(s): CLANGPDB
```

### Version Information

```text
Commit: 68456d8ac19
```

### Urgency

High

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

`/home/khaalid/Documents/edk2/MdeModulePkg/Universal/BdsDxe/BdsEntry.c:1037:7: error: variable 'BootSuccess' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
 1037 |   if (!PlatformRecovery) {
      |       ^~~~~~~~~~~~~~~~~
/home/khaalid/Documents/edk2/MdeModulePkg/Universal/BdsDxe/BdsEntry.c:1113:8: note: uninitialized use occurs here
 1113 |   if (!BootSuccess) {
      |        ^~~~~~~~~~~
/home/khaalid/Documents/edk2/MdeModulePkg/Universal/BdsDxe/BdsEntry.c:1037:3: note: remove the 'if' if its condition is always true
 1037 |   if (!PlatformRecovery) {
      |   ^~~~~~~~~~~~~~~~~~~~~~
/home/khaalid/Documents/edk2/MdeModulePkg/Universal/BdsDxe/BdsEntry.c:694:46: note: initialize the variable 'BootSuccess' to silence this warning
  694 |   BOOLEAN                         BootSuccess;
      |                                              ^
      |                                               = '\0'
1 error generated.
make: *** [GNUmakefile:438: /home/khaalid/Documents/edk2/Build/OvmfX64/DEBUG_CLANGPDB/X64/MdeModulePkg/Universal/BdsDxe/BdsDxe/OUTPUT/BdsEntry.obj] Error 1
`

### PR DESCRIPTION
**Pull request by khaliid2040**
# Description

I combined multiple commits that resolves two three issues in one PR. Please let me know if i need to seperate into seperate PRs.

This PR:
 - Fixes #11786 
 - Fixes #11787 
 - Fixes #11793

There were a build failure with clang 21.1.6 used to build OVMF target architecture X64. The components failed with the build are HiiDatabaseDxe,SetupBrowserDxe and BsdDxe.

Build failed with -Werror,-Wsometimes-uninitialized. Variables not initialized for the two components are 'Status', 'Storage', 'BrowserStorage' and 'BootSuccess'.

Please refer the issues for more information. 
- [ ] Breaking change?
  - NO
- [ ] Impacts security?
  - NO
- [ ] Includes tests?
  - NO

## How This Was Tested
OVMF Image with target architecture X64

## Integration Instructions
N/A

### CODE REVIEW

**Comment by khaliid2040** [comment]
@AshrafAliS It seems some compiler flags are being changed. it is not only CLANG also i saw some issues for VS2022.

Please review the third commit and let me know if i need to change something.

Also i may send more if i observe them. So please be patient with me

Thanks

File: MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c [hunk 1]
```diff
@@ -795,6 +795,7 @@ CompareNameElementDefault (
 
   AppendString  = NULL;
   NvConfigExist = NULL;
+  Status        = EFI_SUCCESS;
```
Comment (apop5) [inline MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c]: I think this should be EFI_OUT_OF_RESOURCES.

Whenever an error occurs with StrStr, it will goto exit, and it needs an error condition to reflect that a failure occured.

File: MdeModulePkg/Universal/BdsDxe/BdsEntry.c [hunk 2]
```diff
@@ -1034,6 +1034,7 @@ BdsEntry (
     EfiBootManagerBoot (&BootManagerMenu);
   }
 
+  BootSuccess = FALSE;
```
Comment (apop5) [inline MdeModulePkg/Universal/BdsDxe/BdsEntry.c]: Any reason that this would not just be moved to the top of the function?

File: MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c (hunk 1 above)
Comment (khaliid2040) [reply MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c]: Thanks, for the suggestion.

I also set Status to EFI_SUCCESS before goto statement so it doesn't always return EFI_OUT_OF_RESOURCES.

**Comment by khaliid2040** [comment]
Resolved in #11803
