### ISSUE TITLE
BaseTools fails to compile with Xcode 7.3

### ISSUE THREAD

**Issue by theracermaster** [tianocore/edk2#89]
Compilation of BaseTools (`make -C BaseTools`) fails with Xcode 7.3 (on OS X 10.11.4) due to negative shifts in FvLib.c.

```
FvLib.c:197:128: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
  *NextFile = (EFI_FFS_FILE_HEADER *) ((((UINTN) CurrentFile - (UINTN) mFvHeader + GetFfsFileLength(CurrentFile) + 0x07) & (-1 << 3)) + (UINT8 *) mFvHeader);
                                                                                                                            ~~ ^
FvLib.c:482:171: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
    CurrentSection.CommonHeader = (EFI_COMMON_SECTION_HEADER *) ((((UINTN) CurrentSection.CommonHeader) + GetSectionFileLength(CurrentSection.CommonHeader) + 0x03) & (-1 << 2));
                                                                                                                                                                       ~~ ^
```

[`-Wno-shift-negative-value` could be added to the Makefile](http://www.insanelymac.com/forum/topic/306156-clover-bugissue-report-and-patch/?p=2234676) to suppress the errors. The negative shifts could also [be replaced](http://www.insanelymac.com/forum/topic/306156-clover-bugissue-report-and-patch/?p=2234682).

**Comment by ajfish** [comment]
From a pedantic point of view shifting negative numbers is undefined behavior in C so the correct fix is casting to an unsigned value. Thus -1 should be -1U (or -1ULL), this is a better fix that suppressing the warning.

**Comment by lersek** [comment]
Duplicate of https://github.com/tianocore/edk2/issues/49, closing.
