### PR TITLE
MdeModulePkg/DxeCapsuleLibFmp: Fix compilation error

### PR DESCRIPTION
**Pull request by nhivp**
# Description

The commit "MdeModulePkg/DxeCapsuleLibFmp: Fix crash if no ESRT is found" leads to a compilation error in
MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.inf. The issue occurs because the variable mDxeCapsuleLibReadyToBootEvent which is declared as extern does not exist, while it is defined in DxeCapsuleRuntime.c, a file not included in DxeCapsuleLib.inf. This patch is to fix this by moving the variable defintion to DxeCapsuleLib.c and declare it as extern in DxeCapsuleRuntime.c.

Reported-by: Gua Guo <gua.guo@intel.com>

- [ ] Breaking change?
  - **Breaking change** - Will this cause a break in build or boot behavior?
  - Examples: Add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests or integration tests.

### CODE REVIEW

**Review by gguo11837463 — APPROVED** [review]

**Review by mdkinney — APPROVED** [review]

**Comment by mdkinney** [comment]
Fixes build break introduced by https://github.com/tianocore/edk2/pull/5692

**Review by lgao4 — APPROVED** [review]
