### PR TITLE
UefiPayloadPkg: Fix build failure with GCC introduced by #6026

### PR DESCRIPTION
**Pull request by khaliid2040**
# Description

UefiPayloadPkg fails to build with gcc due missing type casting. ParseCapsules accepts type with BL_CAPSULE_CALLBACK however a void function is given which resulted following build failure.

```
/home/khaalid/Documents/edk2/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c: In function ‘BuildHobFromBl’:
/home/khaalid/Documents/edk2/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c:476:27: error: passing argument 1 of ‘ParseCapsules’ from incompatible pointer type [-Wincompatible-pointer-types]
  476 |   Status = ParseCapsules (BuildCvHob);
      |                           ^~~~~~~~~~
      |                           |
      |                           void (__attribute__((ms_abi)) *)(EFI_PHYSICAL_ADDRESS,  UINT64) {aka void (__attribute__((ms_abi)) *)(long long unsigned int,  long long unsigned int)}
In file included from /home/khaalid/Documents/edk2/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.h:24,
                 from /home/khaalid/Documents/edk2/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c:12:
/home/khaalid/Documents/edk2/UefiPayloadPkg/Include/Library/BlParseLib.h:184:27: note: expected ‘BL_CAPSULE_CALLBACK’ {aka ‘void (*)(long long unsigned int,  long long unsigned int)’} but argument is of type ‘void (__attribute__((ms_abi)) *)(EFI_PHYSICAL_ADDRESS,  UINT64)’ {aka ‘void (__attribute__((ms_abi)) *)(long long unsigned int,  long long unsigned int)’}
  184 |   IN BL_CAPSULE_CALLBACK  CapsuleCallback
      |      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from /home/khaalid/Documents/edk2/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.h:19:
/home/khaalid/Documents/edk2/MdePkg/Include/Library/HobLib.h:387:1: note: ‘BuildCvHob’ declared here
  387 | BuildCvHob (
      | ^~~~~~~~~~
/home/khaalid/Documents/edk2/UefiPayloadPkg/Include/Library/BlParseLib.h:31:3: note: ‘BL_CAPSULE_CALLBACK’ declared here
   31 | (*BL_CAPSULE_CALLBACK) (
      |   ^~~~~~~~~~~~~~~~~~~
make: *** [GNUmakefile:383: /home/khaalid/Documents/edk2/Build/UefiPayloadPkgLegacy/DEBUG_GCC5/X64/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry/OUTPUT/UefiPayloadEntry.obj] Error 1

```

casting to BL_CAPSULE_CALLBACK should fix the issue. The code resulted this regression is introduced by #6026
- [ ] Breaking change?
  - NO
- [ ] Impacts security?
  - NO
- [ ] Includes tests?
  - NO

## How This Was Tested

run following command:
```
source edksetup.sh
build -a X64 -p UefiPayloadPkg/UefiPayloadPkg.dsc -t GCC5 -b DEBUG
```

## Integration Instructions
N/A

### CODE REVIEW

**Comment by mikebeaton** [comment]
BL_CAPSULE_CALLBACK is missing EFIAPI.

Should be:
```
typedef VOID \
(EFIAPI *BL_CAPSULE_CALLBACK) (
  EFI_PHYSICAL_ADDRESS  BaseAddress,
  UINT64                Length
  );
```
and no cast required.

**Comment by mikebeaton** [comment]
Hi - In the past @leiflindholm has asked me to include in the commit message a tag `Fixes: .....` with the SHA of the commit which introduced the issue (e.g. [here](https://github.com/tianocore/edk2/pull/11738/changes/4e84786df1d0b63f16a92b2641634e68ae1a2a64#r2510320245) & [here](https://github.com/tianocore/edk2/pull/11738/changes/9cca1a0aa974ef8563aaf31c75fd7531dd92cad7#r2510277717)).

Along these lines I believe it would be useful to add `Fixes: cc149a8eaab5f09d021c035d81132bd6f21760e3` in the commit message here, if you agree.

**Comment by khaliid2040** [comment]
cc: @benjamindoron, @ChaselChiu, @gguo11837463, @jameslu8 , @Sean-StarLabs, @shuoliu0 

Can you please review this PR, and if you are okay with the changes i would like to ask to merge as soon as possible so the issue get fixed.

**Review by gguo11837463 — APPROVED** [review]
