### ISSUE TITLE
IntelFsp2Pkg: Fix build failure (FSP 2.4 Multi-Phase Interface) (Bugzilla Bug 4049)

### ISSUE THREAD

**Issue by tianocore-issues** [tianocore/edk2#9194]
This issue was created automatically with [bugzilla2github](https://github.com/makubacki/bugzilla2github/tree/bz2gh_tianocore)
# Bugzilla Bug 4049
Date: 2022-09-06T23:16:09+00:00
From: @makubacki
To:   @ChaselChiu
CC:   @ChaselChiu

Last updated: 2022-09-15T14:27:24+00:00

**Comment by tianocore-issues** [comment]
## Comment 19503
Date: 2022-09-06 23:16:09 +0000
From: @makubacki

- Industry Specification: ---
- Release Observed: EDK II Master
- Releases to Fix: EDK II Master
- Target OS: ---
- Bugzilla Assignee(s): @ChaselChiu

The following commit in IntelFsp2Pkg introduced the FSP 2.4 Multi-Phase interface:

https://github.com/tianocore/edk2/commit/df25a5457f04ec465dce97428cfee96f462676e7

Files such as IntelFsp2Pkg/FspSecCore/Fsp24SecCoreM.inf and IntelFsp2Pkg/FspSecCore/Fsp24SecCoreS.inf were added to IntelFsp2Pkg.dsc but the files were not added to the package.

BZ4048 enables CI in these packages. It is recommended to merge those changes and then enable the compiler check plugin in IntelFsp2Pkg.ci.yaml which will include compilation in CI and then verify all CI checks pass with the future change for this BZ.

**Comment by tianocore-issues** [comment]
## Comment 19504
Date: 2022-09-06 23:49:42 +0000
From: @makubacki

Chasel, are you willing to take this BZ?

**Comment by tianocore-issues** [comment]
## Comment 19507
Date: 2022-09-07 00:22:31 +0000
From: @ChaselChiu

I thought the Fsp24SecCore modules should be merged separately later after platforms resolved the library dependency, but actually we should be able to merge Fsp24SecCore modules now and platforms should adopt new modules only when all dependency resolved.

patch merged: https://github.com/tianocore/edk2/commit/3d35a6c243ffe749a2ae71d5d72ce0361f168f49

Please help to check if this CI build issue resolved with latest code base.

**Comment by tianocore-issues** [comment]
## Comment 19509
Date: 2022-09-07 01:08:12 +0000
From: @makubacki

(In reply to Chasel from comment #2)
&gt; I thought the Fsp24SecCore modules should be merged separately later after
&gt; platforms resolved the library dependency, but actually we should be able to
&gt; merge Fsp24SecCore modules now and platforms should adopt new modules only
&gt; when all dependency resolved.
&gt; 
&gt; patch merged:
&gt; https://github.com/tianocore/edk2/commit/
&gt; 3d35a6c243ffe749a2ae71d5d72ce0361f168f49
&gt; 
&gt; Please help to check if this CI build issue resolved with latest code base.

I know I mentioned this to you outside this BZ, but to keep things in sync here, I&apos;m still seeing this linker failure with 3d35a6c:

ERROR - Linker #2001 from BaseFspSecPlatformLibNull.lib(Flat32.obj) :   unresolved external symbol _TempRamInitApi
ERROR - Linker #1120 from \edk2\Build\IntelFsp2Pkg\DEBUG_VS2019\IA32\IntelFsp2Pkg\FspSecCore\FspSecCoreI\DEBUG\FspSecCoreI.dll : fatal   1 unresolved externals

**Comment by tianocore-issues** [comment]
## Comment 19515
Date: 2022-09-07 12:03:44 +0000
From: @ChaselChiu

Created attachment 1020
test patch for fixing FspSecCoreI linker failure.

Somehow VS2015 did not see such build failure, would you also share what&apos;s the build environment which reproduce this issue? I also attached the test patch for fixing this build failure, please help to check if issue resolved.

Attachment: [BZ-1020-0001-IntelFsp2Pkg-Fix-FspSecCoreI-build-failure.patch](https://github.com/tianocore/user-attachments/raw/refs/heads/main/tianocore/edk2/BZ-1020-0001-IntelFsp2Pkg-Fix-FspSecCoreI-build-failure.patch)

**Comment by tianocore-issues** [comment]
## Comment 19520
Date: 2022-09-07 15:28:34 +0000
From: @makubacki

(In reply to Chasel from comment #4)
&gt; Created attachment 1020 [details]
&gt; test patch for fixing FspSecCoreI linker failure.
&gt; 
&gt; Somehow VS2015 did not see such build failure, would you also share what&apos;s
&gt; the build environment which reproduce this issue? I also attached the test
&gt; patch for fixing this build failure, please help to check if issue resolved.

Yes, with that patch, CI with VS2019 now passes

This is why we need CI :)

**Comment by tianocore-issues** [comment]
## Comment 19571
Date: 2022-09-15 13:31:30 +0000
From: @ChaselChiu

Patch merged:
https://github.com/tianocore/edk2/commit/f46c7d1e36c901e72cc0daee8429275bcb319eb9

Please help to double check if still any build failure.

**Comment by tianocore-issues** [comment]
## Comment 19572
Date: 2022-09-15 14:27:24 +0000
From: @makubacki

Issue is fixed. I&apos;ll mark this as resolved.
