### ISSUE TITLE
[Bug]: SetupBrowserDxe build fails with CLANGPDB

### ISSUE THREAD

**Issue by khaliid2040** [tianocore/edk2#11786]
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

MdeModulePkg

### Which targets are impacted by this bug?

DEBUG

### Current Behavior

Build fails with clang 21.1.6 due uninitialized variables. Variables 'Storage' and 'BrowserStorage' resulted:
-Werror,-Wsometimes-uninitialized

### Expected Behavior

Build with clang 21.1.6 to be successful.

### Steps To Reproduce

1. Install clang and required toolchain like LLVM and lld.
2. Build with OVMF target architecture X64.
3. Make sure MdeModulePkg/Universal/SetupBrowserDxe is included in the build
4. It should fail with provided build errors

### Build Environment

```markdown
- OS(s): Arch Linux
- Tool Chain(s): CLANGPDB
```

### Version Information

```text
Commit: 1436aea4d57 - 1436aea4d57
```

### Urgency

High

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

`make: Nothing to be done for 'tbuild'.
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:9: error: variable 'Storage' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  456 |     if (StorageName == NULL) {
      |         ^~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:523:7: note: uninitialized use occurs here
  523 |   if (Storage != NULL) {
      |       ^~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:5: note: remove the 'if' if its condition is always false
Building ... /home/khaalid/edk2/SecurityPkg/Hash2DxeCrypto/Hash2DxeCrypto.inf [X64]
  456 |     if (StorageName == NULL) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |       ASSERT (StorageName != NULL);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  458 |       goto ErrorExit;
      |       ~~~~~~~~~~~~~~~
  459 |     }
      |     ~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:426:28: note: initialize the variable 'Storage' to silence this warning
  426 |   FORMSET_STORAGE  *Storage;
      |                            ^
      |                             = NULL
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:470:7: error: variable 'BrowserStorage' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  470 |   if (Storage == NULL) {
      |       ^~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:519:7: note: uninitialized use occurs here
  519 |   if (BrowserStorage != NULL) {
      |       ^~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:470:3: note: remove the 'if' if its condition is always false
  470 |   if (Storage == NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~
  471 |     ASSERT (Storage != NULL);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~
  472 |     goto ErrorExit;
      |     ~~~~~~~~~~~~~~~
  473 |   }
      |   ~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:9: error: variable 'BrowserStorage' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  456 |     if (StorageName == NULL) {
      |         ^~~~~~~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:519:7: note: uninitialized use occurs here
  519 |   if (BrowserStorage != NULL) {
      |       ^~~~~~~~~~~~~~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:456:5: note: remove the 'if' if its condition is always false
  456 |     if (StorageName == NULL) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |       ASSERT (StorageName != NULL);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  458 |       goto ErrorExit;
      |       ~~~~~~~~~~~~~~~
  459 |     }
      |     ~
/home/khaalid/edk2/MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c:429:35: note: initialize the variable 'BrowserStorage' to silence this warning
  429 |   BROWSER_STORAGE  *BrowserStorage;
      |                                   ^
      |                                    = NULL
`

**Comment by khaliid2040** [comment]
Apparently, build failure isn't specific to toolchain version.

**Comment by khaliid2040** [comment]
Fixed in #11803
